{
# 公众号配置
# 公众号appId
"app_id": "wxe1c684dc7b1c6012",
# 公众号appSecret
"app_secret": "c83dfe0cfdcb5e6ef7865a83f583be01",
# 模板消息id
"template_id": "1eitS1Prd6mKpBmfrNsJgrc6ywpHcAtm1EG1GIJ9ABo	",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["ovEDL5zJpkxerL1kbDrNjAN_-nKo"],

# 信息配置
# 所在省份
"province": "贵州",
# 所在城市
"city": "贵阳",
# 生日1，修改name为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1": {"陈希婷": "小仙女", "birthday": "r1999-08-13"},
# 生日2
"birthday2": {"苏淼": "小可爱", "birthday": "r2000-01-26"},
# 在一起的日子，格式同上
"love_date": "2022-09-11"
}
